export { departamentoSlice } from './departamentoSlice';
export { cargoSlice } from './cargoSlice';
export { empleadoSlice } from './empleadoSlice';
export { usuarioSlice } from './usuarioSlice';
export { rolSlice } from './rolSlice';
export { contratoSlice } from './contratoSlice';
export { horarioSlice } from './horarioSlice';
export { diasVacacionSlice } from './diasVacacionSlice';
export { bonoAntiguedadSlice } from './bonoAntiguedadSlice';
export { solicitudSlice } from './solicitudSlice';
import asistenciaReducer from './asistenciaSlice';